### ISSUE TITLE
shadowrootの場合、上位のCSSを適用する方法を考える

### ISSUE THREAD

**Issue by mogera551** [mogera551/quel#19]
[Shadow DOM の CSS 管理方法](https://tech.basicinc.jp/articles/159)

上位のCSSにtitle属性に名前を付けておいて、それを適用するみたいな感じ
※代替スタイルシートも参照
styleタグの中に指定できないか？

```html
<style title="cssname">
</style>
```

```css
::root {
  --adopt-style: cssname;
}

```
